// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/oauthgrant"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/oauthtoken"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// OAuthTokenUpdate is the builder for updating OAuthToken entities.
type OAuthTokenUpdate struct {
	config
	hooks    []Hook
	mutation *OAuthTokenMutation
}

// Where appends a list predicates to the OAuthTokenUpdate builder.
func (_u *OAuthTokenUpdate) Where(ps ...predicate.OAuthToken) *OAuthTokenUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthTokenUpdate) SetUpdatedAt(v time.Time) *OAuthTokenUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetKind sets the "kind" field.
func (_u *OAuthTokenUpdate) SetKind(v oauthtoken.Kind) *OAuthTokenUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *OAuthTokenUpdate) SetNillableKind(v *oauthtoken.Kind) *OAuthTokenUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *OAuthTokenUpdate) SetTokenHash(v []byte) *OAuthTokenUpdate {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *OAuthTokenUpdate) SetExpiresAt(v time.Time) *OAuthTokenUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *OAuthTokenUpdate) SetNillableExpiresAt(v *time.Time) *OAuthTokenUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUsedAt sets the "used_at" field.
func (_u *OAuthTokenUpdate) SetUsedAt(v time.Time) *OAuthTokenUpdate {
	_u.mutation.SetUsedAt(v)
	return _u
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_u *OAuthTokenUpdate) SetNillableUsedAt(v *time.Time) *OAuthTokenUpdate {
	if v != nil {
		_u.SetUsedAt(*v)
	}
	return _u
}

// ClearUsedAt clears the value of the "used_at" field.
func (_u *OAuthTokenUpdate) ClearUsedAt() *OAuthTokenUpdate {
	_u.mutation.ClearUsedAt()
	return _u
}

// SetCodeChallenge sets the "code_challenge" field.
func (_u *OAuthTokenUpdate) SetCodeChallenge(v string) *OAuthTokenUpdate {
	_u.mutation.SetCodeChallenge(v)
	return _u
}

// SetNillableCodeChallenge sets the "code_challenge" field if the given value is not nil.
func (_u *OAuthTokenUpdate) SetNillableCodeChallenge(v *string) *OAuthTokenUpdate {
	if v != nil {
		_u.SetCodeChallenge(*v)
	}
	return _u
}

// ClearCodeChallenge clears the value of the "code_challenge" field.
func (_u *OAuthTokenUpdate) ClearCodeChallenge() *OAuthTokenUpdate {
	_u.mutation.ClearCodeChallenge()
	return _u
}

// SetRedirectURI sets the "redirect_uri" field.
func (_u *OAuthTokenUpdate) SetRedirectURI(v string) *OAuthTokenUpdate {
	_u.mutation.SetRedirectURI(v)
	return _u
}

// SetNillableRedirectURI sets the "redirect_uri" field if the given value is not nil.
func (_u *OAuthTokenUpdate) SetNillableRedirectURI(v *string) *OAuthTokenUpdate {
	if v != nil {
		_u.SetRedirectURI(*v)
	}
	return _u
}

// ClearRedirectURI clears the value of the "redirect_uri" field.
func (_u *OAuthTokenUpdate) ClearRedirectURI() *OAuthTokenUpdate {
	_u.mutation.ClearRedirectURI()
	return _u
}

// SetGrantID sets the "grant" edge to the OAuthGrant entity by ID.
func (_u *OAuthTokenUpdate) SetGrantID(id uuid.UUID) *OAuthTokenUpdate {
	_u.mutation.SetGrantID(id)
	return _u
}

// SetGrant sets the "grant" edge to the OAuthGrant entity.
func (_u *OAuthTokenUpdate) SetGrant(v *OAuthGrant) *OAuthTokenUpdate {
	return _u.SetGrantID(v.ID)
}

// Mutation returns the OAuthTokenMutation object of the builder.
func (_u *OAuthTokenUpdate) Mutation() *OAuthTokenMutation {
	return _u.mutation
}

// ClearGrant clears the "grant" edge to the OAuthGrant entity.
func (_u *OAuthTokenUpdate) ClearGrant() *OAuthTokenUpdate {
	_u.mutation.ClearGrant()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OAuthTokenUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OAuthTokenUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthTokenUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthTokenUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oauthtoken.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthTokenUpdate) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := oauthtoken.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "OAuthToken.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CodeChallenge(); ok {
		if err := oauthtoken.CodeChallengeValidator(v); err != nil {
			return &ValidationError{Name: "code_challenge", err: fmt.Errorf(`ent: validator failed for field "OAuthToken.code_challenge": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RedirectURI(); ok {
		if err := oauthtoken.RedirectURIValidator(v); err != nil {
			return &ValidationError{Name: "redirect_uri", err: fmt.Errorf(`ent: validator failed for field "OAuthToken.redirect_uri": %w`, err)}
		}
	}
	if _u.mutation.GrantCleared() && len(_u.mutation.GrantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OAuthToken.grant"`)
	}
	return nil
}

func (_u *OAuthTokenUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthtoken.Table, oauthtoken.Columns, sqlgraph.NewFieldSpec(oauthtoken.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthtoken.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(oauthtoken.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(oauthtoken.FieldTokenHash, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthtoken.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UsedAt(); ok {
		_spec.SetField(oauthtoken.FieldUsedAt, field.TypeTime, value)
	}
	if _u.mutation.UsedAtCleared() {
		_spec.ClearField(oauthtoken.FieldUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CodeChallenge(); ok {
		_spec.SetField(oauthtoken.FieldCodeChallenge, field.TypeString, value)
	}
	if _u.mutation.CodeChallengeCleared() {
		_spec.ClearField(oauthtoken.FieldCodeChallenge, field.TypeString)
	}
	if value, ok := _u.mutation.RedirectURI(); ok {
		_spec.SetField(oauthtoken.FieldRedirectURI, field.TypeString, value)
	}
	if _u.mutation.RedirectURICleared() {
		_spec.ClearField(oauthtoken.FieldRedirectURI, field.TypeString)
	}
	if _u.mutation.GrantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthtoken.GrantTable,
			Columns: []string{oauthtoken.GrantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthgrant.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GrantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthtoken.GrantTable,
			Columns: []string{oauthtoken.GrantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthgrant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthtoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OAuthTokenUpdateOne is the builder for updating a single OAuthToken entity.
type OAuthTokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OAuthTokenMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthTokenUpdateOne) SetUpdatedAt(v time.Time) *OAuthTokenUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetKind sets the "kind" field.
func (_u *OAuthTokenUpdateOne) SetKind(v oauthtoken.Kind) *OAuthTokenUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *OAuthTokenUpdateOne) SetNillableKind(v *oauthtoken.Kind) *OAuthTokenUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *OAuthTokenUpdateOne) SetTokenHash(v []byte) *OAuthTokenUpdateOne {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *OAuthTokenUpdateOne) SetExpiresAt(v time.Time) *OAuthTokenUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *OAuthTokenUpdateOne) SetNillableExpiresAt(v *time.Time) *OAuthTokenUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUsedAt sets the "used_at" field.
func (_u *OAuthTokenUpdateOne) SetUsedAt(v time.Time) *OAuthTokenUpdateOne {
	_u.mutation.SetUsedAt(v)
	return _u
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_u *OAuthTokenUpdateOne) SetNillableUsedAt(v *time.Time) *OAuthTokenUpdateOne {
	if v != nil {
		_u.SetUsedAt(*v)
	}
	return _u
}

// ClearUsedAt clears the value of the "used_at" field.
func (_u *OAuthTokenUpdateOne) ClearUsedAt() *OAuthTokenUpdateOne {
	_u.mutation.ClearUsedAt()
	return _u
}

// SetCodeChallenge sets the "code_challenge" field.
func (_u *OAuthTokenUpdateOne) SetCodeChallenge(v string) *OAuthTokenUpdateOne {
	_u.mutation.SetCodeChallenge(v)
	return _u
}

// SetNillableCodeChallenge sets the "code_challenge" field if the given value is not nil.
func (_u *OAuthTokenUpdateOne) SetNillableCodeChallenge(v *string) *OAuthTokenUpdateOne {
	if v != nil {
		_u.SetCodeChallenge(*v)
	}
	return _u
}

// ClearCodeChallenge clears the value of the "code_challenge" field.
func (_u *OAuthTokenUpdateOne) ClearCodeChallenge() *OAuthTokenUpdateOne {
	_u.mutation.ClearCodeChallenge()
	return _u
}

// SetRedirectURI sets the "redirect_uri" field.
func (_u *OAuthTokenUpdateOne) SetRedirectURI(v string) *OAuthTokenUpdateOne {
	_u.mutation.SetRedirectURI(v)
	return _u
}

// SetNillableRedirectURI sets the "redirect_uri" field if the given value is not nil.
func (_u *OAuthTokenUpdateOne) SetNillableRedirectURI(v *string) *OAuthTokenUpdateOne {
	if v != nil {
		_u.SetRedirectURI(*v)
	}
	return _u
}

// ClearRedirectURI clears the value of the "redirect_uri" field.
func (_u *OAuthTokenUpdateOne) ClearRedirectURI() *OAuthTokenUpdateOne {
	_u.mutation.ClearRedirectURI()
	return _u
}

// SetGrantID sets the "grant" edge to the OAuthGrant entity by ID.
func (_u *OAuthTokenUpdateOne) SetGrantID(id uuid.UUID) *OAuthTokenUpdateOne {
	_u.mutation.SetGrantID(id)
	return _u
}

// SetGrant sets the "grant" edge to the OAuthGrant entity.
func (_u *OAuthTokenUpdateOne) SetGrant(v *OAuthGrant) *OAuthTokenUpdateOne {
	return _u.SetGrantID(v.ID)
}

// Mutation returns the OAuthTokenMutation object of the builder.
func (_u *OAuthTokenUpdateOne) Mutation() *OAuthTokenMutation {
	return _u.mutation
}

// ClearGrant clears the "grant" edge to the OAuthGrant entity.
func (_u *OAuthTokenUpdateOne) ClearGrant() *OAuthTokenUpdateOne {
	_u.mutation.ClearGrant()
	return _u
}

// Where appends a list predicates to the OAuthTokenUpdate builder.
func (_u *OAuthTokenUpdateOne) Where(ps ...predicate.OAuthToken) *OAuthTokenUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OAuthTokenUpdateOne) Select(field string, fields ...string) *OAuthTokenUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OAuthToken entity.
func (_u *OAuthTokenUpdateOne) Save(ctx context.Context) (*OAuthToken, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthTokenUpdateOne) SaveX(ctx context.Context) *OAuthToken {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OAuthTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthTokenUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthTokenUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oauthtoken.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthTokenUpdateOne) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := oauthtoken.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "OAuthToken.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CodeChallenge(); ok {
		if err := oauthtoken.CodeChallengeValidator(v); err != nil {
			return &ValidationError{Name: "code_challenge", err: fmt.Errorf(`ent: validator failed for field "OAuthToken.code_challenge": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RedirectURI(); ok {
		if err := oauthtoken.RedirectURIValidator(v); err != nil {
			return &ValidationError{Name: "redirect_uri", err: fmt.Errorf(`ent: validator failed for field "OAuthToken.redirect_uri": %w`, err)}
		}
	}
	if _u.mutation.GrantCleared() && len(_u.mutation.GrantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OAuthToken.grant"`)
	}
	return nil
}

func (_u *OAuthTokenUpdateOne) sqlSave(ctx context.Context) (_node *OAuthToken, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthtoken.Table, oauthtoken.Columns, sqlgraph.NewFieldSpec(oauthtoken.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OAuthToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthtoken.FieldID)
		for _, f := range fields {
			if !oauthtoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != oauthtoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthtoken.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(oauthtoken.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(oauthtoken.FieldTokenHash, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthtoken.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UsedAt(); ok {
		_spec.SetField(oauthtoken.FieldUsedAt, field.TypeTime, value)
	}
	if _u.mutation.UsedAtCleared() {
		_spec.ClearField(oauthtoken.FieldUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CodeChallenge(); ok {
		_spec.SetField(oauthtoken.FieldCodeChallenge, field.TypeString, value)
	}
	if _u.mutation.CodeChallengeCleared() {
		_spec.ClearField(oauthtoken.FieldCodeChallenge, field.TypeString)
	}
	if value, ok := _u.mutation.RedirectURI(); ok {
		_spec.SetField(oauthtoken.FieldRedirectURI, field.TypeString, value)
	}
	if _u.mutation.RedirectURICleared() {
		_spec.ClearField(oauthtoken.FieldRedirectURI, field.TypeString)
	}
	if _u.mutation.GrantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthtoken.GrantTable,
			Columns: []string{oauthtoken.GrantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthgrant.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GrantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthtoken.GrantTable,
			Columns: []string{oauthtoken.GrantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthgrant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OAuthToken{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthtoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
