// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/group"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/oauthclient"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/oauthgrant"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/oauthtoken"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/user"
)

// OAuthGrantUpdate is the builder for updating OAuthGrant entities.
type OAuthGrantUpdate struct {
	config
	hooks    []Hook
	mutation *OAuthGrantMutation
}

// Where appends a list predicates to the OAuthGrantUpdate builder.
func (_u *OAuthGrantUpdate) Where(ps ...predicate.OAuthGrant) *OAuthGrantUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthGrantUpdate) SetUpdatedAt(v time.Time) *OAuthGrantUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OAuthGrantUpdate) SetUserID(v uuid.UUID) *OAuthGrantUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OAuthGrantUpdate) SetNillableUserID(v *uuid.UUID) *OAuthGrantUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *OAuthGrantUpdate) SetGroupID(v uuid.UUID) *OAuthGrantUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *OAuthGrantUpdate) SetNillableGroupID(v *uuid.UUID) *OAuthGrantUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *OAuthGrantUpdate) SetScopes(v []string) *OAuthGrantUpdate {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *OAuthGrantUpdate) AppendScopes(v []string) *OAuthGrantUpdate {
	_u.mutation.AppendScopes(v)
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *OAuthGrantUpdate) SetLastUsedAt(v time.Time) *OAuthGrantUpdate {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *OAuthGrantUpdate) SetNillableLastUsedAt(v *time.Time) *OAuthGrantUpdate {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *OAuthGrantUpdate) ClearLastUsedAt() *OAuthGrantUpdate {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *OAuthGrantUpdate) SetUser(v *User) *OAuthGrantUpdate {
	return _u.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *OAuthGrantUpdate) SetGroup(v *Group) *OAuthGrantUpdate {
	return _u.SetGroupID(v.ID)
}

// SetClientID sets the "client" edge to the OAuthClient entity by ID.
func (_u *OAuthGrantUpdate) SetClientID(id uuid.UUID) *OAuthGrantUpdate {
	_u.mutation.SetClientID(id)
	return _u
}

// SetClient sets the "client" edge to the OAuthClient entity.
func (_u *OAuthGrantUpdate) SetClient(v *OAuthClient) *OAuthGrantUpdate {
	return _u.SetClientID(v.ID)
}

// AddTokenIDs adds the "tokens" edge to the OAuthToken entity by IDs.
func (_u *OAuthGrantUpdate) AddTokenIDs(ids ...uuid.UUID) *OAuthGrantUpdate {
	_u.mutation.AddTokenIDs(ids...)
	return _u
}

// AddTokens adds the "tokens" edges to the OAuthToken entity.
func (_u *OAuthGrantUpdate) AddTokens(v ...*OAuthToken) *OAuthGrantUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTokenIDs(ids...)
}

// Mutation returns the OAuthGrantMutation object of the builder.
func (_u *OAuthGrantUpdate) Mutation() *OAuthGrantMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *OAuthGrantUpdate) ClearUser() *OAuthGrantUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *OAuthGrantUpdate) ClearGroup() *OAuthGrantUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// ClearClient clears the "client" edge to the OAuthClient entity.
func (_u *OAuthGrantUpdate) ClearClient() *OAuthGrantUpdate {
	_u.mutation.ClearClient()
	return _u
}

// ClearTokens clears all "tokens" edges to the OAuthToken entity.
func (_u *OAuthGrantUpdate) ClearTokens() *OAuthGrantUpdate {
	_u.mutation.ClearTokens()
	return _u
}

// RemoveTokenIDs removes the "tokens" edge to OAuthToken entities by IDs.
func (_u *OAuthGrantUpdate) RemoveTokenIDs(ids ...uuid.UUID) *OAuthGrantUpdate {
	_u.mutation.RemoveTokenIDs(ids...)
	return _u
}

// RemoveTokens removes "tokens" edges to OAuthToken entities.
func (_u *OAuthGrantUpdate) RemoveTokens(v ...*OAuthToken) *OAuthGrantUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTokenIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OAuthGrantUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthGrantUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OAuthGrantUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthGrantUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthGrantUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oauthgrant.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthGrantUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OAuthGrant.user"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OAuthGrant.group"`)
	}
	if _u.mutation.ClientCleared() && len(_u.mutation.ClientIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OAuthGrant.client"`)
	}
	return nil
}

func (_u *OAuthGrantUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthgrant.Table, oauthgrant.Columns, sqlgraph.NewFieldSpec(oauthgrant.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthgrant.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(oauthgrant.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthgrant.FieldScopes, value)
		})
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(oauthgrant.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(oauthgrant.FieldLastUsedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthgrant.UserTable,
			Columns: []string{oauthgrant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthgrant.UserTable,
			Columns: []string{oauthgrant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthgrant.GroupTable,
			Columns: []string{oauthgrant.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthgrant.GroupTable,
			Columns: []string{oauthgrant.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ClientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthgrant.ClientTable,
			Columns: []string{oauthgrant.ClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthgrant.ClientTable,
			Columns: []string{oauthgrant.ClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthgrant.TokensTable,
			Columns: []string{oauthgrant.TokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthtoken.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTokensIDs(); len(nodes) > 0 && !_u.mutation.TokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthgrant.TokensTable,
			Columns: []string{oauthgrant.TokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthtoken.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthgrant.TokensTable,
			Columns: []string{oauthgrant.TokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthtoken.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthgrant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OAuthGrantUpdateOne is the builder for updating a single OAuthGrant entity.
type OAuthGrantUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OAuthGrantMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthGrantUpdateOne) SetUpdatedAt(v time.Time) *OAuthGrantUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OAuthGrantUpdateOne) SetUserID(v uuid.UUID) *OAuthGrantUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OAuthGrantUpdateOne) SetNillableUserID(v *uuid.UUID) *OAuthGrantUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *OAuthGrantUpdateOne) SetGroupID(v uuid.UUID) *OAuthGrantUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *OAuthGrantUpdateOne) SetNillableGroupID(v *uuid.UUID) *OAuthGrantUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *OAuthGrantUpdateOne) SetScopes(v []string) *OAuthGrantUpdateOne {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *OAuthGrantUpdateOne) AppendScopes(v []string) *OAuthGrantUpdateOne {
	_u.mutation.AppendScopes(v)
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *OAuthGrantUpdateOne) SetLastUsedAt(v time.Time) *OAuthGrantUpdateOne {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *OAuthGrantUpdateOne) SetNillableLastUsedAt(v *time.Time) *OAuthGrantUpdateOne {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *OAuthGrantUpdateOne) ClearLastUsedAt() *OAuthGrantUpdateOne {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *OAuthGrantUpdateOne) SetUser(v *User) *OAuthGrantUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *OAuthGrantUpdateOne) SetGroup(v *Group) *OAuthGrantUpdateOne {
	return _u.SetGroupID(v.ID)
}

// SetClientID sets the "client" edge to the OAuthClient entity by ID.
func (_u *OAuthGrantUpdateOne) SetClientID(id uuid.UUID) *OAuthGrantUpdateOne {
	_u.mutation.SetClientID(id)
	return _u
}

// SetClient sets the "client" edge to the OAuthClient entity.
func (_u *OAuthGrantUpdateOne) SetClient(v *OAuthClient) *OAuthGrantUpdateOne {
	return _u.SetClientID(v.ID)
}

// AddTokenIDs adds the "tokens" edge to the OAuthToken entity by IDs.
func (_u *OAuthGrantUpdateOne) AddTokenIDs(ids ...uuid.UUID) *OAuthGrantUpdateOne {
	_u.mutation.AddTokenIDs(ids...)
	return _u
}

// AddTokens adds the "tokens" edges to the OAuthToken entity.
func (_u *OAuthGrantUpdateOne) AddTokens(v ...*OAuthToken) *OAuthGrantUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTokenIDs(ids...)
}

// Mutation returns the OAuthGrantMutation object of the builder.
func (_u *OAuthGrantUpdateOne) Mutation() *OAuthGrantMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *OAuthGrantUpdateOne) ClearUser() *OAuthGrantUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *OAuthGrantUpdateOne) ClearGroup() *OAuthGrantUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// ClearClient clears the "client" edge to the OAuthClient entity.
func (_u *OAuthGrantUpdateOne) ClearClient() *OAuthGrantUpdateOne {
	_u.mutation.ClearClient()
	return _u
}

// ClearTokens clears all "tokens" edges to the OAuthToken entity.
func (_u *OAuthGrantUpdateOne) ClearTokens() *OAuthGrantUpdateOne {
	_u.mutation.ClearTokens()
	return _u
}

// RemoveTokenIDs removes the "tokens" edge to OAuthToken entities by IDs.
func (_u *OAuthGrantUpdateOne) RemoveTokenIDs(ids ...uuid.UUID) *OAuthGrantUpdateOne {
	_u.mutation.RemoveTokenIDs(ids...)
	return _u
}

// RemoveTokens removes "tokens" edges to OAuthToken entities.
func (_u *OAuthGrantUpdateOne) RemoveTokens(v ...*OAuthToken) *OAuthGrantUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTokenIDs(ids...)
}

// Where appends a list predicates to the OAuthGrantUpdate builder.
func (_u *OAuthGrantUpdateOne) Where(ps ...predicate.OAuthGrant) *OAuthGrantUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OAuthGrantUpdateOne) Select(field string, fields ...string) *OAuthGrantUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OAuthGrant entity.
func (_u *OAuthGrantUpdateOne) Save(ctx context.Context) (*OAuthGrant, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthGrantUpdateOne) SaveX(ctx context.Context) *OAuthGrant {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OAuthGrantUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthGrantUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthGrantUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oauthgrant.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthGrantUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OAuthGrant.user"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OAuthGrant.group"`)
	}
	if _u.mutation.ClientCleared() && len(_u.mutation.ClientIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OAuthGrant.client"`)
	}
	return nil
}

func (_u *OAuthGrantUpdateOne) sqlSave(ctx context.Context) (_node *OAuthGrant, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthgrant.Table, oauthgrant.Columns, sqlgraph.NewFieldSpec(oauthgrant.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OAuthGrant.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthgrant.FieldID)
		for _, f := range fields {
			if !oauthgrant.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != oauthgrant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthgrant.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(oauthgrant.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthgrant.FieldScopes, value)
		})
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(oauthgrant.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(oauthgrant.FieldLastUsedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthgrant.UserTable,
			Columns: []string{oauthgrant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthgrant.UserTable,
			Columns: []string{oauthgrant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthgrant.GroupTable,
			Columns: []string{oauthgrant.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthgrant.GroupTable,
			Columns: []string{oauthgrant.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ClientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthgrant.ClientTable,
			Columns: []string{oauthgrant.ClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthgrant.ClientTable,
			Columns: []string{oauthgrant.ClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthgrant.TokensTable,
			Columns: []string{oauthgrant.TokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthtoken.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTokensIDs(); len(nodes) > 0 && !_u.mutation.TokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthgrant.TokensTable,
			Columns: []string{oauthgrant.TokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthtoken.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthgrant.TokensTable,
			Columns: []string{oauthgrant.TokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthtoken.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OAuthGrant{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthgrant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
