// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/oauthclient"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/oauthrequest"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// OAuthRequestUpdate is the builder for updating OAuthRequest entities.
type OAuthRequestUpdate struct {
	config
	hooks    []Hook
	mutation *OAuthRequestMutation
}

// Where appends a list predicates to the OAuthRequestUpdate builder.
func (_u *OAuthRequestUpdate) Where(ps ...predicate.OAuthRequest) *OAuthRequestUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthRequestUpdate) SetUpdatedAt(v time.Time) *OAuthRequestUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRedirectURI sets the "redirect_uri" field.
func (_u *OAuthRequestUpdate) SetRedirectURI(v string) *OAuthRequestUpdate {
	_u.mutation.SetRedirectURI(v)
	return _u
}

// SetNillableRedirectURI sets the "redirect_uri" field if the given value is not nil.
func (_u *OAuthRequestUpdate) SetNillableRedirectURI(v *string) *OAuthRequestUpdate {
	if v != nil {
		_u.SetRedirectURI(*v)
	}
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *OAuthRequestUpdate) SetScopes(v []string) *OAuthRequestUpdate {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *OAuthRequestUpdate) AppendScopes(v []string) *OAuthRequestUpdate {
	_u.mutation.AppendScopes(v)
	return _u
}

// SetState sets the "state" field.
func (_u *OAuthRequestUpdate) SetState(v string) *OAuthRequestUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *OAuthRequestUpdate) SetNillableState(v *string) *OAuthRequestUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// ClearState clears the value of the "state" field.
func (_u *OAuthRequestUpdate) ClearState() *OAuthRequestUpdate {
	_u.mutation.ClearState()
	return _u
}

// SetCodeChallenge sets the "code_challenge" field.
func (_u *OAuthRequestUpdate) SetCodeChallenge(v string) *OAuthRequestUpdate {
	_u.mutation.SetCodeChallenge(v)
	return _u
}

// SetNillableCodeChallenge sets the "code_challenge" field if the given value is not nil.
func (_u *OAuthRequestUpdate) SetNillableCodeChallenge(v *string) *OAuthRequestUpdate {
	if v != nil {
		_u.SetCodeChallenge(*v)
	}
	return _u
}

// SetResource sets the "resource" field.
func (_u *OAuthRequestUpdate) SetResource(v string) *OAuthRequestUpdate {
	_u.mutation.SetResource(v)
	return _u
}

// SetNillableResource sets the "resource" field if the given value is not nil.
func (_u *OAuthRequestUpdate) SetNillableResource(v *string) *OAuthRequestUpdate {
	if v != nil {
		_u.SetResource(*v)
	}
	return _u
}

// ClearResource clears the value of the "resource" field.
func (_u *OAuthRequestUpdate) ClearResource() *OAuthRequestUpdate {
	_u.mutation.ClearResource()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *OAuthRequestUpdate) SetExpiresAt(v time.Time) *OAuthRequestUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *OAuthRequestUpdate) SetNillableExpiresAt(v *time.Time) *OAuthRequestUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetClientID sets the "client" edge to the OAuthClient entity by ID.
func (_u *OAuthRequestUpdate) SetClientID(id uuid.UUID) *OAuthRequestUpdate {
	_u.mutation.SetClientID(id)
	return _u
}

// SetClient sets the "client" edge to the OAuthClient entity.
func (_u *OAuthRequestUpdate) SetClient(v *OAuthClient) *OAuthRequestUpdate {
	return _u.SetClientID(v.ID)
}

// Mutation returns the OAuthRequestMutation object of the builder.
func (_u *OAuthRequestUpdate) Mutation() *OAuthRequestMutation {
	return _u.mutation
}

// ClearClient clears the "client" edge to the OAuthClient entity.
func (_u *OAuthRequestUpdate) ClearClient() *OAuthRequestUpdate {
	_u.mutation.ClearClient()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OAuthRequestUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthRequestUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OAuthRequestUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthRequestUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthRequestUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oauthrequest.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthRequestUpdate) check() error {
	if v, ok := _u.mutation.RedirectURI(); ok {
		if err := oauthrequest.RedirectURIValidator(v); err != nil {
			return &ValidationError{Name: "redirect_uri", err: fmt.Errorf(`ent: validator failed for field "OAuthRequest.redirect_uri": %w`, err)}
		}
	}
	if v, ok := _u.mutation.State(); ok {
		if err := oauthrequest.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "OAuthRequest.state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CodeChallenge(); ok {
		if err := oauthrequest.CodeChallengeValidator(v); err != nil {
			return &ValidationError{Name: "code_challenge", err: fmt.Errorf(`ent: validator failed for field "OAuthRequest.code_challenge": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Resource(); ok {
		if err := oauthrequest.ResourceValidator(v); err != nil {
			return &ValidationError{Name: "resource", err: fmt.Errorf(`ent: validator failed for field "OAuthRequest.resource": %w`, err)}
		}
	}
	if _u.mutation.ClientCleared() && len(_u.mutation.ClientIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OAuthRequest.client"`)
	}
	return nil
}

func (_u *OAuthRequestUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthrequest.Table, oauthrequest.Columns, sqlgraph.NewFieldSpec(oauthrequest.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthrequest.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RedirectURI(); ok {
		_spec.SetField(oauthrequest.FieldRedirectURI, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(oauthrequest.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthrequest.FieldScopes, value)
		})
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(oauthrequest.FieldState, field.TypeString, value)
	}
	if _u.mutation.StateCleared() {
		_spec.ClearField(oauthrequest.FieldState, field.TypeString)
	}
	if value, ok := _u.mutation.CodeChallenge(); ok {
		_spec.SetField(oauthrequest.FieldCodeChallenge, field.TypeString, value)
	}
	if value, ok := _u.mutation.Resource(); ok {
		_spec.SetField(oauthrequest.FieldResource, field.TypeString, value)
	}
	if _u.mutation.ResourceCleared() {
		_spec.ClearField(oauthrequest.FieldResource, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthrequest.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ClientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthrequest.ClientTable,
			Columns: []string{oauthrequest.ClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthrequest.ClientTable,
			Columns: []string{oauthrequest.ClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthrequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OAuthRequestUpdateOne is the builder for updating a single OAuthRequest entity.
type OAuthRequestUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OAuthRequestMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthRequestUpdateOne) SetUpdatedAt(v time.Time) *OAuthRequestUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRedirectURI sets the "redirect_uri" field.
func (_u *OAuthRequestUpdateOne) SetRedirectURI(v string) *OAuthRequestUpdateOne {
	_u.mutation.SetRedirectURI(v)
	return _u
}

// SetNillableRedirectURI sets the "redirect_uri" field if the given value is not nil.
func (_u *OAuthRequestUpdateOne) SetNillableRedirectURI(v *string) *OAuthRequestUpdateOne {
	if v != nil {
		_u.SetRedirectURI(*v)
	}
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *OAuthRequestUpdateOne) SetScopes(v []string) *OAuthRequestUpdateOne {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *OAuthRequestUpdateOne) AppendScopes(v []string) *OAuthRequestUpdateOne {
	_u.mutation.AppendScopes(v)
	return _u
}

// SetState sets the "state" field.
func (_u *OAuthRequestUpdateOne) SetState(v string) *OAuthRequestUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *OAuthRequestUpdateOne) SetNillableState(v *string) *OAuthRequestUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// ClearState clears the value of the "state" field.
func (_u *OAuthRequestUpdateOne) ClearState() *OAuthRequestUpdateOne {
	_u.mutation.ClearState()
	return _u
}

// SetCodeChallenge sets the "code_challenge" field.
func (_u *OAuthRequestUpdateOne) SetCodeChallenge(v string) *OAuthRequestUpdateOne {
	_u.mutation.SetCodeChallenge(v)
	return _u
}

// SetNillableCodeChallenge sets the "code_challenge" field if the given value is not nil.
func (_u *OAuthRequestUpdateOne) SetNillableCodeChallenge(v *string) *OAuthRequestUpdateOne {
	if v != nil {
		_u.SetCodeChallenge(*v)
	}
	return _u
}

// SetResource sets the "resource" field.
func (_u *OAuthRequestUpdateOne) SetResource(v string) *OAuthRequestUpdateOne {
	_u.mutation.SetResource(v)
	return _u
}

// SetNillableResource sets the "resource" field if the given value is not nil.
func (_u *OAuthRequestUpdateOne) SetNillableResource(v *string) *OAuthRequestUpdateOne {
	if v != nil {
		_u.SetResource(*v)
	}
	return _u
}

// ClearResource clears the value of the "resource" field.
func (_u *OAuthRequestUpdateOne) ClearResource() *OAuthRequestUpdateOne {
	_u.mutation.ClearResource()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *OAuthRequestUpdateOne) SetExpiresAt(v time.Time) *OAuthRequestUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *OAuthRequestUpdateOne) SetNillableExpiresAt(v *time.Time) *OAuthRequestUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetClientID sets the "client" edge to the OAuthClient entity by ID.
func (_u *OAuthRequestUpdateOne) SetClientID(id uuid.UUID) *OAuthRequestUpdateOne {
	_u.mutation.SetClientID(id)
	return _u
}

// SetClient sets the "client" edge to the OAuthClient entity.
func (_u *OAuthRequestUpdateOne) SetClient(v *OAuthClient) *OAuthRequestUpdateOne {
	return _u.SetClientID(v.ID)
}

// Mutation returns the OAuthRequestMutation object of the builder.
func (_u *OAuthRequestUpdateOne) Mutation() *OAuthRequestMutation {
	return _u.mutation
}

// ClearClient clears the "client" edge to the OAuthClient entity.
func (_u *OAuthRequestUpdateOne) ClearClient() *OAuthRequestUpdateOne {
	_u.mutation.ClearClient()
	return _u
}

// Where appends a list predicates to the OAuthRequestUpdate builder.
func (_u *OAuthRequestUpdateOne) Where(ps ...predicate.OAuthRequest) *OAuthRequestUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OAuthRequestUpdateOne) Select(field string, fields ...string) *OAuthRequestUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OAuthRequest entity.
func (_u *OAuthRequestUpdateOne) Save(ctx context.Context) (*OAuthRequest, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthRequestUpdateOne) SaveX(ctx context.Context) *OAuthRequest {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OAuthRequestUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthRequestUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthRequestUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oauthrequest.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthRequestUpdateOne) check() error {
	if v, ok := _u.mutation.RedirectURI(); ok {
		if err := oauthrequest.RedirectURIValidator(v); err != nil {
			return &ValidationError{Name: "redirect_uri", err: fmt.Errorf(`ent: validator failed for field "OAuthRequest.redirect_uri": %w`, err)}
		}
	}
	if v, ok := _u.mutation.State(); ok {
		if err := oauthrequest.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "OAuthRequest.state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CodeChallenge(); ok {
		if err := oauthrequest.CodeChallengeValidator(v); err != nil {
			return &ValidationError{Name: "code_challenge", err: fmt.Errorf(`ent: validator failed for field "OAuthRequest.code_challenge": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Resource(); ok {
		if err := oauthrequest.ResourceValidator(v); err != nil {
			return &ValidationError{Name: "resource", err: fmt.Errorf(`ent: validator failed for field "OAuthRequest.resource": %w`, err)}
		}
	}
	if _u.mutation.ClientCleared() && len(_u.mutation.ClientIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OAuthRequest.client"`)
	}
	return nil
}

func (_u *OAuthRequestUpdateOne) sqlSave(ctx context.Context) (_node *OAuthRequest, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthrequest.Table, oauthrequest.Columns, sqlgraph.NewFieldSpec(oauthrequest.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OAuthRequest.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthrequest.FieldID)
		for _, f := range fields {
			if !oauthrequest.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != oauthrequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthrequest.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RedirectURI(); ok {
		_spec.SetField(oauthrequest.FieldRedirectURI, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(oauthrequest.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthrequest.FieldScopes, value)
		})
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(oauthrequest.FieldState, field.TypeString, value)
	}
	if _u.mutation.StateCleared() {
		_spec.ClearField(oauthrequest.FieldState, field.TypeString)
	}
	if value, ok := _u.mutation.CodeChallenge(); ok {
		_spec.SetField(oauthrequest.FieldCodeChallenge, field.TypeString, value)
	}
	if value, ok := _u.mutation.Resource(); ok {
		_spec.SetField(oauthrequest.FieldResource, field.TypeString, value)
	}
	if _u.mutation.ResourceCleared() {
		_spec.ClearField(oauthrequest.FieldResource, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthrequest.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ClientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthrequest.ClientTable,
			Columns: []string{oauthrequest.ClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthrequest.ClientTable,
			Columns: []string{oauthrequest.ClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OAuthRequest{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthrequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
