// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/oauthgrant"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/oauthtoken"
)

// OAuthTokenCreate is the builder for creating a OAuthToken entity.
type OAuthTokenCreate struct {
	config
	mutation *OAuthTokenMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *OAuthTokenCreate) SetCreatedAt(v time.Time) *OAuthTokenCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OAuthTokenCreate) SetNillableCreatedAt(v *time.Time) *OAuthTokenCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OAuthTokenCreate) SetUpdatedAt(v time.Time) *OAuthTokenCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OAuthTokenCreate) SetNillableUpdatedAt(v *time.Time) *OAuthTokenCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetKind sets the "kind" field.
func (_c *OAuthTokenCreate) SetKind(v oauthtoken.Kind) *OAuthTokenCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetTokenHash sets the "token_hash" field.
func (_c *OAuthTokenCreate) SetTokenHash(v []byte) *OAuthTokenCreate {
	_c.mutation.SetTokenHash(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *OAuthTokenCreate) SetExpiresAt(v time.Time) *OAuthTokenCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetUsedAt sets the "used_at" field.
func (_c *OAuthTokenCreate) SetUsedAt(v time.Time) *OAuthTokenCreate {
	_c.mutation.SetUsedAt(v)
	return _c
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_c *OAuthTokenCreate) SetNillableUsedAt(v *time.Time) *OAuthTokenCreate {
	if v != nil {
		_c.SetUsedAt(*v)
	}
	return _c
}

// SetCodeChallenge sets the "code_challenge" field.
func (_c *OAuthTokenCreate) SetCodeChallenge(v string) *OAuthTokenCreate {
	_c.mutation.SetCodeChallenge(v)
	return _c
}

// SetNillableCodeChallenge sets the "code_challenge" field if the given value is not nil.
func (_c *OAuthTokenCreate) SetNillableCodeChallenge(v *string) *OAuthTokenCreate {
	if v != nil {
		_c.SetCodeChallenge(*v)
	}
	return _c
}

// SetRedirectURI sets the "redirect_uri" field.
func (_c *OAuthTokenCreate) SetRedirectURI(v string) *OAuthTokenCreate {
	_c.mutation.SetRedirectURI(v)
	return _c
}

// SetNillableRedirectURI sets the "redirect_uri" field if the given value is not nil.
func (_c *OAuthTokenCreate) SetNillableRedirectURI(v *string) *OAuthTokenCreate {
	if v != nil {
		_c.SetRedirectURI(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OAuthTokenCreate) SetID(v uuid.UUID) *OAuthTokenCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *OAuthTokenCreate) SetNillableID(v *uuid.UUID) *OAuthTokenCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetGrantID sets the "grant" edge to the OAuthGrant entity by ID.
func (_c *OAuthTokenCreate) SetGrantID(id uuid.UUID) *OAuthTokenCreate {
	_c.mutation.SetGrantID(id)
	return _c
}

// SetGrant sets the "grant" edge to the OAuthGrant entity.
func (_c *OAuthTokenCreate) SetGrant(v *OAuthGrant) *OAuthTokenCreate {
	return _c.SetGrantID(v.ID)
}

// Mutation returns the OAuthTokenMutation object of the builder.
func (_c *OAuthTokenCreate) Mutation() *OAuthTokenMutation {
	return _c.mutation
}

// Save creates the OAuthToken in the database.
func (_c *OAuthTokenCreate) Save(ctx context.Context) (*OAuthToken, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OAuthTokenCreate) SaveX(ctx context.Context) *OAuthToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthTokenCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthTokenCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OAuthTokenCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := oauthtoken.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := oauthtoken.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := oauthtoken.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OAuthTokenCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OAuthToken.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OAuthToken.updated_at"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "OAuthToken.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := oauthtoken.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "OAuthToken.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TokenHash(); !ok {
		return &ValidationError{Name: "token_hash", err: errors.New(`ent: missing required field "OAuthToken.token_hash"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "OAuthToken.expires_at"`)}
	}
	if v, ok := _c.mutation.CodeChallenge(); ok {
		if err := oauthtoken.CodeChallengeValidator(v); err != nil {
			return &ValidationError{Name: "code_challenge", err: fmt.Errorf(`ent: validator failed for field "OAuthToken.code_challenge": %w`, err)}
		}
	}
	if v, ok := _c.mutation.RedirectURI(); ok {
		if err := oauthtoken.RedirectURIValidator(v); err != nil {
			return &ValidationError{Name: "redirect_uri", err: fmt.Errorf(`ent: validator failed for field "OAuthToken.redirect_uri": %w`, err)}
		}
	}
	if len(_c.mutation.GrantIDs()) == 0 {
		return &ValidationError{Name: "grant", err: errors.New(`ent: missing required edge "OAuthToken.grant"`)}
	}
	return nil
}

func (_c *OAuthTokenCreate) sqlSave(ctx context.Context) (*OAuthToken, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OAuthTokenCreate) createSpec() (*OAuthToken, *sqlgraph.CreateSpec) {
	var (
		_node = &OAuthToken{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oauthtoken.Table, sqlgraph.NewFieldSpec(oauthtoken.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(oauthtoken.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthtoken.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(oauthtoken.FieldKind, field.TypeEnum, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.TokenHash(); ok {
		_spec.SetField(oauthtoken.FieldTokenHash, field.TypeBytes, value)
		_node.TokenHash = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthtoken.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.UsedAt(); ok {
		_spec.SetField(oauthtoken.FieldUsedAt, field.TypeTime, value)
		_node.UsedAt = &value
	}
	if value, ok := _c.mutation.CodeChallenge(); ok {
		_spec.SetField(oauthtoken.FieldCodeChallenge, field.TypeString, value)
		_node.CodeChallenge = value
	}
	if value, ok := _c.mutation.RedirectURI(); ok {
		_spec.SetField(oauthtoken.FieldRedirectURI, field.TypeString, value)
		_node.RedirectURI = value
	}
	if nodes := _c.mutation.GrantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthtoken.GrantTable,
			Columns: []string{oauthtoken.GrantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthgrant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.oauth_grant_tokens = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OAuthTokenCreateBulk is the builder for creating many OAuthToken entities in bulk.
type OAuthTokenCreateBulk struct {
	config
	err      error
	builders []*OAuthTokenCreate
}

// Save creates the OAuthToken entities in the database.
func (_c *OAuthTokenCreateBulk) Save(ctx context.Context) ([]*OAuthToken, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OAuthToken, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OAuthTokenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OAuthTokenCreateBulk) SaveX(ctx context.Context) []*OAuthToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthTokenCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthTokenCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
