// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/oauthclient"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/oauthrequest"
)

// OAuthRequestCreate is the builder for creating a OAuthRequest entity.
type OAuthRequestCreate struct {
	config
	mutation *OAuthRequestMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *OAuthRequestCreate) SetCreatedAt(v time.Time) *OAuthRequestCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OAuthRequestCreate) SetNillableCreatedAt(v *time.Time) *OAuthRequestCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OAuthRequestCreate) SetUpdatedAt(v time.Time) *OAuthRequestCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OAuthRequestCreate) SetNillableUpdatedAt(v *time.Time) *OAuthRequestCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetRedirectURI sets the "redirect_uri" field.
func (_c *OAuthRequestCreate) SetRedirectURI(v string) *OAuthRequestCreate {
	_c.mutation.SetRedirectURI(v)
	return _c
}

// SetScopes sets the "scopes" field.
func (_c *OAuthRequestCreate) SetScopes(v []string) *OAuthRequestCreate {
	_c.mutation.SetScopes(v)
	return _c
}

// SetState sets the "state" field.
func (_c *OAuthRequestCreate) SetState(v string) *OAuthRequestCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *OAuthRequestCreate) SetNillableState(v *string) *OAuthRequestCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetCodeChallenge sets the "code_challenge" field.
func (_c *OAuthRequestCreate) SetCodeChallenge(v string) *OAuthRequestCreate {
	_c.mutation.SetCodeChallenge(v)
	return _c
}

// SetResource sets the "resource" field.
func (_c *OAuthRequestCreate) SetResource(v string) *OAuthRequestCreate {
	_c.mutation.SetResource(v)
	return _c
}

// SetNillableResource sets the "resource" field if the given value is not nil.
func (_c *OAuthRequestCreate) SetNillableResource(v *string) *OAuthRequestCreate {
	if v != nil {
		_c.SetResource(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *OAuthRequestCreate) SetExpiresAt(v time.Time) *OAuthRequestCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *OAuthRequestCreate) SetID(v uuid.UUID) *OAuthRequestCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *OAuthRequestCreate) SetNillableID(v *uuid.UUID) *OAuthRequestCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetClientID sets the "client" edge to the OAuthClient entity by ID.
func (_c *OAuthRequestCreate) SetClientID(id uuid.UUID) *OAuthRequestCreate {
	_c.mutation.SetClientID(id)
	return _c
}

// SetClient sets the "client" edge to the OAuthClient entity.
func (_c *OAuthRequestCreate) SetClient(v *OAuthClient) *OAuthRequestCreate {
	return _c.SetClientID(v.ID)
}

// Mutation returns the OAuthRequestMutation object of the builder.
func (_c *OAuthRequestCreate) Mutation() *OAuthRequestMutation {
	return _c.mutation
}

// Save creates the OAuthRequest in the database.
func (_c *OAuthRequestCreate) Save(ctx context.Context) (*OAuthRequest, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OAuthRequestCreate) SaveX(ctx context.Context) *OAuthRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthRequestCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthRequestCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OAuthRequestCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := oauthrequest.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := oauthrequest.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := oauthrequest.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OAuthRequestCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OAuthRequest.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OAuthRequest.updated_at"`)}
	}
	if _, ok := _c.mutation.RedirectURI(); !ok {
		return &ValidationError{Name: "redirect_uri", err: errors.New(`ent: missing required field "OAuthRequest.redirect_uri"`)}
	}
	if v, ok := _c.mutation.RedirectURI(); ok {
		if err := oauthrequest.RedirectURIValidator(v); err != nil {
			return &ValidationError{Name: "redirect_uri", err: fmt.Errorf(`ent: validator failed for field "OAuthRequest.redirect_uri": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Scopes(); !ok {
		return &ValidationError{Name: "scopes", err: errors.New(`ent: missing required field "OAuthRequest.scopes"`)}
	}
	if v, ok := _c.mutation.State(); ok {
		if err := oauthrequest.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "OAuthRequest.state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CodeChallenge(); !ok {
		return &ValidationError{Name: "code_challenge", err: errors.New(`ent: missing required field "OAuthRequest.code_challenge"`)}
	}
	if v, ok := _c.mutation.CodeChallenge(); ok {
		if err := oauthrequest.CodeChallengeValidator(v); err != nil {
			return &ValidationError{Name: "code_challenge", err: fmt.Errorf(`ent: validator failed for field "OAuthRequest.code_challenge": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Resource(); ok {
		if err := oauthrequest.ResourceValidator(v); err != nil {
			return &ValidationError{Name: "resource", err: fmt.Errorf(`ent: validator failed for field "OAuthRequest.resource": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "OAuthRequest.expires_at"`)}
	}
	if len(_c.mutation.ClientIDs()) == 0 {
		return &ValidationError{Name: "client", err: errors.New(`ent: missing required edge "OAuthRequest.client"`)}
	}
	return nil
}

func (_c *OAuthRequestCreate) sqlSave(ctx context.Context) (*OAuthRequest, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OAuthRequestCreate) createSpec() (*OAuthRequest, *sqlgraph.CreateSpec) {
	var (
		_node = &OAuthRequest{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oauthrequest.Table, sqlgraph.NewFieldSpec(oauthrequest.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(oauthrequest.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthrequest.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.RedirectURI(); ok {
		_spec.SetField(oauthrequest.FieldRedirectURI, field.TypeString, value)
		_node.RedirectURI = value
	}
	if value, ok := _c.mutation.Scopes(); ok {
		_spec.SetField(oauthrequest.FieldScopes, field.TypeJSON, value)
		_node.Scopes = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(oauthrequest.FieldState, field.TypeString, value)
		_node.State = value
	}
	if value, ok := _c.mutation.CodeChallenge(); ok {
		_spec.SetField(oauthrequest.FieldCodeChallenge, field.TypeString, value)
		_node.CodeChallenge = value
	}
	if value, ok := _c.mutation.Resource(); ok {
		_spec.SetField(oauthrequest.FieldResource, field.TypeString, value)
		_node.Resource = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthrequest.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if nodes := _c.mutation.ClientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthrequest.ClientTable,
			Columns: []string{oauthrequest.ClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.oauth_client_requests = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OAuthRequestCreateBulk is the builder for creating many OAuthRequest entities in bulk.
type OAuthRequestCreateBulk struct {
	config
	err      error
	builders []*OAuthRequestCreate
}

// Save creates the OAuthRequest entities in the database.
func (_c *OAuthRequestCreateBulk) Save(ctx context.Context) ([]*OAuthRequest, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OAuthRequest, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OAuthRequestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OAuthRequestCreateBulk) SaveX(ctx context.Context) []*OAuthRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthRequestCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthRequestCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
